version: '2.3'
services:
  images2karte:
    build: .
    container_name: colab-local-runtime
    ports:
      - "8888:8888"
    runtime: nvidia
    volumes:
      - ".:/workspace"
    working_dir: /workspace
    environment:
      TZ: Asia/Tokyo
    command: >
      jupyter notebook
        --allow-root
        --ip=0.0.0.0
        --port=8888
        --NotebookApp.token=''
        --NotebookApp.allow_origin='https://colab.research.google.com'
