version: '2.3'
services:
  jupyterlab:
    build: .
    ports:
      - "8888:8888"
    runtime: nvidia
    volumes:
      - "./datasets:/workspace/datasets"
      - "./outputs:/workspace/outputs"
      - "./notes:/workspace/notes"
      - "./.jupyter:/root/.jupyter"
      - "./.ipython/profile_default/ipython_config.py:/root/.ipython/profile_default/ipython_config.py"
    working_dir: /workspace
    privileged: true
    environment:
      TZ: Asia/Tokyo
    restart: unless-stopped
    command: jupyter notebook
